# Generated by Django 5.0.6 on 2024-06-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(upload_to='car/media/uploads/'),
        ),
    ]
